//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.BuildingSupervisors = new HashSet<BuildingSupervisor>();
            this.ClassesLeaders = new HashSet<ClassesLeader>();
            this.EmployeeClasses = new HashSet<EmployeeClass>();
            this.EmployeesDelays = new HashSet<EmployeesDelay>();
            this.EmployeesDiscounts = new HashSet<EmployeesDiscount>();
            this.EmployeesIncreases = new HashSet<EmployeesIncreas>();
            this.EmployeesReceipts = new HashSet<EmployeesReceipt>();
            this.EmployeesTransferAllowances = new HashSet<EmployeesTransferAllowance>();
            this.EmployeesVacations = new HashSet<EmployeesVacation>();
            this.EmployeesWorkShifts = new HashSet<EmployeesWorkShift>();
            this.Expenses = new HashSet<Expens>();
            this.Users = new HashSet<User>();
            this.Revenues = new HashSet<Revenue>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JopId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string BirthDate { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MaritalStateId { get; set; }
        public Nullable<System.Guid> RegistrationTypeId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string JoiningDate { get; set; }
        public Nullable<double> WorkDayCost { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildingSupervisor> BuildingSupervisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassesLeader> ClassesLeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeClass> EmployeeClasses { get; set; }
        public virtual EmployeeRegistrationType EmployeeRegistrationType { get; set; }
        public virtual Jop Jop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesDelay> EmployeesDelays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesDiscount> EmployeesDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesIncreas> EmployeesIncreases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesReceipt> EmployeesReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesTransferAllowance> EmployeesTransferAllowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesVacation> EmployeesVacations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesWorkShift> EmployeesWorkShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenue> Revenues { get; set; }
    }
}
