//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesDiscount
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DiscountTypeId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.DateTime> DiscountDate { get; set; }
        public string DiscountValue { get; set; }
        public string DiscountReason { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual DiscountsType DiscountsType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
