//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesReceipt
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public Nullable<double> TotalAdds { get; set; }
        public Nullable<double> FinalTotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
