//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class almohandes_DbEntities : DbContext
    {
        public almohandes_DbEntities()
            : base("name=almohandes_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildingSupervisor> BuildingSupervisors { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassesLeader> ClassesLeaders { get; set; }
        public virtual DbSet<ClassExam> ClassExams { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Destrict> Destricts { get; set; }
        public virtual DbSet<DiscountsType> DiscountsTypes { get; set; }
        public virtual DbSet<EmployeeClass> EmployeeClasses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesDelay> EmployeesDelays { get; set; }
        public virtual DbSet<EmployeesDiscount> EmployeesDiscounts { get; set; }
        public virtual DbSet<EmployeesIncreas> EmployeesIncreases { get; set; }
        public virtual DbSet<EmployeesTransferAllowance> EmployeesTransferAllowances { get; set; }
        public virtual DbSet<EmployeesVacation> EmployeesVacations { get; set; }
        public virtual DbSet<EmployeesWorkShift> EmployeesWorkShifts { get; set; }
        public virtual DbSet<ExamDegree> ExamDegrees { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<ExamsType> ExamsTypes { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<ExpensesType> ExpensesTypes { get; set; }
        public virtual DbSet<IncreasesType> IncreasesTypes { get; set; }
        public virtual DbSet<Jop> Jops { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<RegistrationType> RegistrationTypes { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenuesType> RevenuesTypes { get; set; }
        public virtual DbSet<ShiftsTime> ShiftsTimes { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsAttendance> StudentsAttendances { get; set; }
        public virtual DbSet<StudentsAttendanceDetail> StudentsAttendanceDetails { get; set; }
        public virtual DbSet<StudentsClass> StudentsClasses { get; set; }
        public virtual DbSet<StudentsExamDegree> StudentsExamDegrees { get; set; }
        public virtual DbSet<StudyClass> StudyClasses { get; set; }
        public virtual DbSet<StudyPlace> StudyPlaces { get; set; }
        public virtual DbSet<StudyType> StudyTypes { get; set; }
        public virtual DbSet<StudyYear> StudyYears { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubscriptionMethod> SubscriptionMethods { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionsType> SubscriptionsTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VacationsType> VacationsTypes { get; set; }
        public virtual DbSet<WorkShift> WorkShifts { get; set; }
    }
}
