//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StudyYearId { get; set; }
        public Nullable<System.Guid> StudyPlaceId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.Guid> RevenueTypeId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<double> RevenueValue { get; set; }
        public Nullable<System.DateTime> RevenueDate { get; set; }
        public Nullable<System.Guid> SubscriptionMethodId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RevenuesType RevenuesType { get; set; }
        public virtual StudyPlace StudyPlace { get; set; }
        public virtual StudyYear StudyYear { get; set; }
        public virtual SubscriptionMethod SubscriptionMethod { get; set; }
    }
}
