//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentsClass()
        {
            this.StudentsClassesTransfers = new HashSet<StudentsClassesTransfer>();
            this.SubscriptionMethods = new HashSet<SubscriptionMethod>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.Guid> StudyYearId { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.Guid> SubscriptionId { get; set; }
        public Nullable<bool> IsAnother { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudyYear StudyYear { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsClassesTransfer> StudentsClassesTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionMethod> SubscriptionMethods { get; set; }
    }
}
