//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentFiles = new HashSet<StudentFile>();
            this.StudentReports = new HashSet<StudentReport>();
            this.StudentsAttendances = new HashSet<StudentsAttendance>();
            this.StudentsClasses = new HashSet<StudentsClass>();
            this.StudentsExamDegrees = new HashSet<StudentsExamDegree>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DestrictId { get; set; }
        public Nullable<System.Guid> RegistrationTypeId { get; set; }
        public string NumberId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string MotherName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PhoneMo { get; set; }
        public string PhoneAth { get; set; }
        public string PhoneOwner { get; set; }
        public string FatherJob { get; set; }
        public string MotherJob { get; set; }
        public string FatherNumberId { get; set; }
        public string MotherNumberId { get; set; }
        public string JoiningDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual Destrict Destrict { get; set; }
        public virtual RegistrationType RegistrationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFile> StudentFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentReport> StudentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsAttendance> StudentsAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsClass> StudentsClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsExamDegree> StudentsExamDegrees { get; set; }
    }
}
